### ISSUE TITLE
Project doesn't work on a machine that uses ASP.Net Core SDK 2.1.5

### ISSUE THREAD

**Issue by AnassL** [jitendraselvam/ImageUpload#1]
Project doesn't work on a machine that uses ASP.Net Core SDK 2.1.5

I copied pasted the code on a working project and used Postman to upload image, but unfortunately got a 
**500 Internal Server Error - NullReferenceException**
[more details here](https://www.codeproject.com/Articles/1256591/Upload-Image-to-NET-Core-2-1-API?msg=5569627#xx5569627xx)

**Comment by jitendraselvam** [comment]
Is the project running on it own ? Because even I am using the same dotnet version and it seems to be working. 

Could you try running the project without pasting on your existing project ?

**Comment by AnassL** [comment]
Once uploaded from GitHub repo it gives dependency error on Microsoft.AspNetCore.Http.Features.

Editing the ImageWriter.csproj file shows the following:

```
  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Http.Features">
      <HintPath>..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.http.features\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll</HintPath>
    </Reference>
  </ItemGroup>
```
You need to replace it with:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.1.1" />
  </ItemGroup>
```

Then when I run the project it goes to api/values instead of api/image
If I replace it in the url, it gives the following errors:

> NullReferenceException: Object reference not set to an instance of an object.
> ImageWriter.Classes.ImageWriter.CheckIfImageFile(IFormFile file) in ImageWriter.cs
> +
>                 file.CopyTo(ms);
> ImageWriter.Classes.ImageWriter.UploadImage(IFormFile file) in ImageWriter.cs
> +
>             if (CheckIfImageFile(file))
> ImageUploader.Handler.ImageHandler.UploadImage(IFormFile file) in ImageHandler.cs
> +
>             var result = await _imageWriter.UploadImage(file);
> ImageUploader.Controllers.ImagesController.UploadImage(IFormFile file) in ImagesController.cs
> +
>             return await _imageHandler.UploadImage(file);
> Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
> System.Threading.Tasks.ValueTask<TResult>.get_Result()

FYI, on my machine, dotnet --version returns 2.1.403

**Comment by jitendraselvam** [comment]
I am assuming that you are navigating to api/images with the browser ? That is a POST method and can only be accessible using postman. The browser will throw an error since there is no GET method. 

The default url to load up is api/values. Do change the launchsettings.json after creating your own GET method in imagecontroller.

**Comment by AnassL** [comment]
Yes, I wanted to see quickly whether when running your project the images controller would return something in the browser. 
Despite I added a GET method to the images controller, using POSTMAN, the POST method throws the error I mentioned above, and here is the error data retrieved from the server logs:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ImageWriter.Classes.ImageWriter.CheckIfImageFile(IFormFile file) in D:\ImageUpload\ImageWriter\Classes\ImageWriter.cs:line 34
>    at ImageWriter.Classes.ImageWriter.UploadImage(IFormFile file) in D:\ImageUpload\ImageWriter\Classes\ImageWriter.cs:line 16
>    at ImageUploader.Handler.ImageHandler.UploadImage(IFormFile file) in D:\ImageUpload\ImageUploader\Handler\ImageHandler.cs:line 26
>    at ImageUploader.Controllers.ImagesController.UploadImage(IFormFile file) in D:\ImageUpload\ImageUploader\Controllers\ImagesController.cs:line 42
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

**Comment by jitendraselvam** [comment]
Sorry for the late response. I think I figured out the error. The wwwroot folder is missing in the project. So whenevr the image writer was trying to write the image into the folder it threw an error. Guess the git ignore is ignoring the wwwroot folder.

**Comment by AnassL** [comment]
I have wwwroot\images folder in my project.
If you place a breakpoint in ImageHandler.cs in the UploadImage async method, you'll notice that 'file' property holds a null value, therefore the method returns null.

**Comment by jitendraselvam** [comment]
I tried to replicate this in two other machines. The only way I could get null was when I called the POST method from postman with key's value not equal to 'file'.
